### ISSUE TITLE
"next action of play sonos-player is ambiguous"

### ISSUE THREAD

**Issue by hamelsveld** [LukevdPalen/pimatic-sonos#1]
Luke, great plugin but get it to play the radio when I come in .... your example rule is not working?!?! :(

if device is present then play sonos-player

this will tell me "next action of play sonos-player is ambiguous"

Can you tell me what I've wrong? buttons in the pimatic gui are working fine...

**Comment by LukevdPalen** [comment]
@hamelsveld thx for reporting, i'm looking into it right now.

**Comment by shd-piste** [comment]
I have the same problem, as i wrote you via mail.
Just chiming in to keep it up!
Thanks for your work!

**Comment by hamelsveld** [comment]
Tnx man :-)

**Comment by LukevdPalen** [comment]
Should be fixed ;)
